component_depth: 1
langauges:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/commons/.*
- ./bin/org/apache/commons/httpclient/.*
- ./bin/org/apache/commons/httpclient/cookie/.*
- ./bin/org/apache/commons/pool/.*
- ./bin/org/apache/commons/pool/impl/.*
- ./bin/org/archive/.*
- ./bin/org/archive/crawler/.*
- ./bin/org/archive/crawler/admin/.*
- ./bin/org/archive/crawler/admin/ui/.*
- ./bin/org/archive/crawler/datamodel/.*
- ./bin/org/archive/crawler/datamodel/credential/.*
- ./bin/org/archive/crawler/deciderules/.*
- ./bin/org/archive/crawler/deciderules/recrawl/.*
- ./bin/org/archive/crawler/doc-files/.*
- ./bin/org/archive/crawler/event/.*
- ./bin/org/archive/crawler/extractor/.*
- ./bin/org/archive/crawler/fetcher/.*
- ./bin/org/archive/crawler/filter/.*
- ./bin/org/archive/crawler/framework/.*
- ./bin/org/archive/crawler/framework/exceptions/.*
- ./bin/org/archive/crawler/frontier/.*
- ./bin/org/archive/crawler/io/.*
- ./bin/org/archive/crawler/postprocessor/.*
- ./bin/org/archive/crawler/prefetch/.*
- ./bin/org/archive/crawler/processor/.*
- ./bin/org/archive/crawler/processor/recrawl/.*
- ./bin/org/archive/crawler/scope/.*
- ./bin/org/archive/crawler/selftest/.*
- ./bin/org/archive/crawler/settings/.*
- ./bin/org/archive/crawler/settings/doc-files/.*
- ./bin/org/archive/crawler/settings/refinements/.*
- ./bin/org/archive/crawler/url/.*
- ./bin/org/archive/crawler/url/canonicalize/.*
- ./bin/org/archive/crawler/util/.*
- ./bin/org/archive/crawler/writer/.*
- ./bin/org/archive/extractor/.*
- ./bin/org/archive/httpclient/.*
- ./bin/org/archive/io/.*
- ./bin/org/archive/io/arc/.*
- ./bin/org/archive/io/warc/.*
- ./bin/org/archive/net/.*
- ./bin/org/archive/net/md5/.*
- ./bin/org/archive/net/rsync/.*
- ./bin/org/archive/net/s3/.*
- ./bin/org/archive/queue/.*
- ./bin/org/archive/uid/.*
- ./bin/org/archive/util/.*
- ./bin/org/archive/util/anvl/.*
- ./bin/org/archive/util/bdbje/.*
- ./bin/org/archive/util/fingerprint/.*
- ./bin/org/archive/util/iterator/.*
- ./bin/org/archive/util/ms/.*
- ./bin/st/.*
- ./bin/st/ata/.*
- ./bin/st/ata/util/.*
- ./lib/.*
- ./testdata/.*
- ./testdata/ms/.*
